const quotes = [
  ["Attitude", "I know my worth, so I never beg for attention."],
  ["Attitude", "Silence becomes powerful when there is nothing worth explaining."],
  ["Attitude", "I walk my own path, even when the crowd chooses another road."],
  ["Attitude", "Dignity will always matter more to me than temporary approval."],
  ["Attitude", "I do not chase people; I protect my purpose."],
  ["Attitude", "Peace is too valuable to trade for unnecessary drama."],
  ["Attitude", "I respect everyone, but trust is earned slowly."],
  ["Attitude", "I am not competing with anyone; I am building my own lane."],
  ["Attitude", "The moment respect disappears, so does my presence."],
  ["Attitude", "I would rather lose people than lose myself."],
  ["Attitude", "My confidence was built from battles nobody saw."],
  ["Attitude", "Not every opinion deserves a reaction from me."],
  ["Attitude", "I stopped proving myself when I realized my actions were enough."],
  ["Attitude", "Being misunderstood is easier than pretending to be someone else."],
  ["Attitude", "I keep my circle small because peace needs space."],
  ["Attitude", "My boundaries are not attitude; they are self-respect."],
  ["Attitude", "I do not need a crowd to feel secure in who I am."],
  ["Attitude", "Some exits are necessary when staying costs your peace."],
  ["Attitude", "I can be kind without being easy to take for granted."],
  ["Attitude", "My standards grew higher when my self-respect grew stronger."],
  ["Attitude", "I do not return to places that taught me how to leave."],
  ["Attitude", "My calmness is not weakness; it is self-control."],
  ["Attitude", "I have nothing to prove to people committed to doubting me."],
  ["Attitude", "I choose authenticity even when it makes me stand alone."],
  ["Attitude", "If the energy feels wrong, I do not force the connection."],
  ["Attitude", "I do not hold grudges; I simply remember lessons."],
  ["Attitude", "The strongest response is often a life lived well."],
  ["Attitude", "I am selective with my energy because I know its value."],
  ["Attitude", "My absence is not punishment; sometimes it is protection."],
  ["Attitude", "I stopped explaining my heart to people who only wanted a reason to judge it."],
  ["Attitude", "I do not need permission to become a better version of myself."],
  ["Attitude", "Respect is mutual, and I never ask for what I am unwilling to give."],
  ["Attitude", "I leave quietly when the situation no longer deserves my effort."],
  ["Attitude", "I am comfortable being the person who chooses peace first."],
  ["Attitude", "My self-respect does not depend on who stays."],
  ["Attitude", "I do not follow trends when I can follow my principles."],
  ["Attitude", "I can forgive someone without giving them the same access again."],
  ["Attitude", "My life is too short for conversations that go nowhere."],
  ["Attitude", "I do not confuse attention with genuine respect."],
  ["Attitude", "I would rather be alone than accepted for a version that is not me."],
  ["Attitude", "My standards are not high; they are simply honest."],
  ["Attitude", "I learned to say no without writing an apology afterward."],
  ["Attitude", "I do not need to win every argument; I need to protect my peace."],
  ["Attitude", "People can misunderstand my distance, but they cannot control it."],
  ["Attitude", "I became quieter when I learned that not every battle deserves me."],
  ["Attitude", "I am not cold; I just stopped giving warmth where it was wasted."],
  ["Attitude", "My character matters more to me than my reputation."],
  ["Attitude", "I do not chase validation from people who cannot value themselves."],
  ["Attitude", "The less I force, the more naturally the right things remain."],
  ["Attitude", "I choose progress over proving a point."],
  ["Attitude", "My standards became boundaries after enough lessons."],
  ["Attitude", "I know when to speak, and I know when silence says enough."],
  ["Attitude", "I do not fear starting over when staying means losing myself."],
  ["Attitude", "I am proud of the person I became without an audience."],
  ["Attitude", "My energy belongs to growth, not gossip."],
  ["Attitude", "I do not need revenge when distance already says everything."],
  ["Attitude", "The right people never require me to beg for basic respect."],
  ["Attitude", "I can stand alone without feeling incomplete."],
  ["Attitude", "My confidence does not need to be loud."],
  ["Attitude", "I stopped taking everything personally when I learned people reveal themselves."],
  ["Attitude", "I do not compete for places where I should be valued naturally."],
  ["Attitude", "My peace is my favorite kind of success."],
  ["Attitude", "I would rather have a clear conscience than a perfect image."],
  ["Attitude", "I do not owe everyone access to my life."],
  ["Attitude", "I protect my name by protecting my choices."],
  ["Attitude", "Some people only miss you when they lose access to you."],
  ["Attitude", "I do not become smaller to make insecure people comfortable."],
  ["Attitude", "My patience has limits, and my boundaries have reasons."],
  ["Attitude", "I choose distance over disrespect every time."],
  ["Attitude", "I do not need to announce my growth; people will notice the difference."],
  ["Attitude", "My strongest flex is being at peace with myself."],
  ["Attitude", "I can walk away without turning the exit into a scene."],
  ["Attitude", "I stopped chasing explanations from people who gave me confusion."],
  ["Attitude", "I do not let temporary people create permanent doubts."],
  ["Attitude", "My life gets better when I stop entertaining what drains me."],
  ["Attitude", "I respect my past without letting it control my present."],
  ["Attitude", "I am not difficult; I simply know what I will no longer accept."],
  ["Attitude", "My silence is sometimes the clearest answer I can give."],
  ["Attitude", "I do not need to be liked to remain true to myself."],
  ["Attitude", "The older I get, the more I value peace over popularity."],
  ["Attitude", "I learned that self-respect sometimes looks like leaving."],
  ["Attitude", "I am not afraid of losing a connection that costs my identity."],
  ["Attitude", "My priorities changed when I understood how valuable time is."],
  ["Attitude", "I do not chase what requires me to abandon myself."],
  ["Attitude", "My confidence grew every time I kept a promise to myself."],
  ["Attitude", "I choose people who bring clarity, not confusion."],
  ["Attitude", "I do not argue with chaos; I remove myself from it."],
  ["Attitude", "My standards protect the life I am trying to build."],
  ["Attitude", "I can be soft-hearted and still have strong boundaries."],
  ["Attitude", "I do not need to respond to every rumor about me."],
  ["Attitude", "My peace does not require everyone to understand me."],
  ["Attitude", "I am done negotiating with disrespect."],
  ["Attitude", "The best version of me does not need everyone's approval."],
  ["Attitude", "I leave room for people who know how to value it."],
  ["Attitude", "I am not chasing attention when I already have direction."],
  ["Attitude", "My attitude is simply the confidence of knowing who I am."],
  ["Attitude", "I do not regret outgrowing what once felt familiar."],
  ["Attitude", "I choose self-respect, even when it makes the road quieter."],
  ["Attitude", "I am enough without having to convince anyone."],
  ["Attitude", "I choose my standards over someone else’s expectations."],
  ["Love", "Loving you feels like finding home in a person."],
  ["Love", "Your smile can turn an ordinary day into a memory."],
  ["Love", "My heart feels safest when I am close to you."],
  ["Love", "I would choose you in every version of this life."],
  ["Love", "You are the reason some days feel worth remembering."],
  ["Love", "With you, even silence feels warm."],
  ["Love", "I never knew peace could look so much like a person."],
  ["Love", "Your presence makes the little moments feel important."],
  ["Love", "I want a lifetime filled with ordinary days beside you."],
  ["Love", "You make my heart slow down in the best way."],
  ["Love", "I love the way you make me feel understood."],
  ["Love", "Somewhere between friendship and forever, I found you."],
  ["Love", "You are my favorite thought at the end of the day."],
  ["Love", "I would rather share a simple life with you than a perfect one without you."],
  ["Love", "Your happiness has a special place in my heart."],
  ["Love", "I still smile when your name appears on my screen."],
  ["Love", "You make love feel gentle instead of complicated."],
  ["Love", "My favorite memories somehow keep finding you in them."],
  ["Love", "I want to grow old and still look at you like the beginning."],
  ["Love", "You are the person I want beside me when life gets messy."],
  ["Love", "I never get tired of choosing you."],
  ["Love", "Your voice has a way of making difficult days softer."],
  ["Love", "I love the little things about you that nobody else notices."],
  ["Love", "You make ordinary conversations feel unforgettable."],
  ["Love", "My heart knows your name better than any song."],
  ["Love", "If home had a heartbeat, I think it would sound like yours."],
  ["Love", "I want to collect moments with you, not things."],
  ["Love", "You are my favorite part of an otherwise ordinary day."],
  ["Love", "I love you in the quiet moments just as much as the exciting ones."],
  ["Love", "You make my world feel less heavy."],
  ["Love", "I want to be the person you feel safe telling everything to."],
  ["Love", "Your hand in mine is still one of my favorite feelings."],
  ["Love", "I did not plan to love you; my heart simply recognized you."],
  ["Love", "You make forever sound less frightening."],
  ["Love", "I love how easily you can make me smile."],
  ["Love", "You are the kind of person I want in every chapter."],
  ["Love", "My heart feels lighter whenever you are near."],
  ["Love", "I would choose your company over a thousand distractions."],
  ["Love", "You are not perfect, and that is part of what makes you precious to me."],
  ["Love", "I love the person I become when I am around you."],
  ["Love", "Your kindness is one of the reasons my heart stayed."],
  ["Love", "I want to know every version of you life creates."],
  ["Love", "You are the calm my heart never knew it needed."],
  ["Love", "Every little moment with you feels worth keeping."],
  ["Love", "I want to make memories that age beautifully with us."],
  ["Love", "Your laugh is one of my favorite sounds in the world."],
  ["Love", "I love that I can be completely myself around you."],
  ["Love", "You make even boring days feel like something special."],
  ["Love", "I would still choose you on the difficult days."],
  ["Love", "Your love feels like a quiet light in a noisy world."],
  ["Love", "I want to be there for the days you feel unstoppable and the days you do not."],
  ["Love", "You are the person I want to tell my smallest stories to."],
  ["Love", "I never want to take your presence for granted."],
  ["Love", "Your eyes still make my heart forget what it was saying."],
  ["Love", "I love how safe honesty feels between us."],
  ["Love", "You make me believe that good love can be peaceful."],
  ["Love", "I would rather build slowly with you than rush into something temporary."],
  ["Love", "You are one of the best things my life did not plan for."],
  ["Love", "My favorite future is the one where you are still beside me."],
  ["Love", "I love the way you remember little details about me."],
  ["Love", "You make distance feel temporary when the heart is certain."],
  ["Love", "I want to celebrate your wins as if they were my own."],
  ["Love", "Your presence is a gift I notice even on normal days."],
  ["Love", "I want to be your comfort after a long day."],
  ["Love", "You are the person my heart searches for in a crowded room."],
  ["Love", "I love how your existence makes my world softer."],
  ["Love", "If I could keep one feeling forever, it would be this feeling of us."],
  ["Love", "You make me want to believe in lasting things."],
  ["Love", "I want more sunsets, late-night talks, and quiet mornings with you."],
  ["Love", "Your love makes me grateful for all the roads that led me here."],
  ["Love", "I never need a special occasion to appreciate you."],
  ["Love", "You are my favorite reason to look forward to tomorrow."],
  ["Love", "I love the way we can laugh at things nobody else would understand."],
  ["Love", "You make the simplest moments feel like secret treasures."],
  ["Love", "I want to know your dreams, not just your habits."],
  ["Love", "Your happiness matters to me even when you do not ask."],
  ["Love", "I love that your presence can say more than a thousand messages."],
  ["Love", "You are the person I would choose when life stops being easy."],
  ["Love", "My heart found something rare in you, and I refuse to take it lightly."],
  ["Love", "I want our story to be made of small, honest moments."],
  ["Love", "You are the comfort I did not know I was searching for."],
  ["Love", "I love the peace that comes from knowing we choose each other."],
  ["Love", "I want to hold your hand through every unexpected chapter."],
  ["Love", "You make me feel seen without asking me to explain everything."],
  ["Love", "I would rather have your genuine smile than a room full of applause."],
  ["Love", "You are proof that love can arrive quietly."],
  ["Love", "I love you beyond the words I know how to say."],
  ["Love", "Your presence has become one of my favorite parts of life."],
  ["Love", "I want to keep learning the language of your heart."],
  ["Love", "You make me want to protect the little things that make us us."],
  ["Love", "I love that being with you never feels like performing."],
  ["Love", "You are my favorite person to do absolutely nothing with."],
  ["Love", "I want our love to feel like friendship that never stopped growing."],
  ["Love", "Even after ordinary days, I find new reasons to love you."],
  ["Love", "You make my heart believe that staying can be beautiful."],
  ["Love", "I would choose a lifetime of little moments with you over one perfect day."],
  ["Love", "You are not just part of my life; you are part of how I experience it."],
  ["Love", "You are the kind of person I would choose in both the easy days and the hard ones."],
  ["Love", "Somewhere in your presence, my heart learned what comfort feels like."],
  ["Love", "I want our love to remain honest even when life is not easy."],
  ["Sad", "Sometimes the person you miss is the reason you hurt."],
  ["Sad", "I smile because explaining the sadness feels harder."],
  ["Sad", "Some memories arrive carrying more weight than they should."],
  ["Sad", "I miss who you were before everything changed."],
  ["Sad", "Not every broken heart makes a sound."],
  ["Sad", "There are goodbyes the heart keeps replaying."],
  ["Sad", "I stopped explaining because some people only listen to reply."],
  ["Sad", "The hardest part was accepting that you were already gone."],
  ["Sad", "Some nights feel longer because memories refuse to sleep."],
  ["Sad", "I still have words I will never send."],
  ["Sad", "I miss the days when your presence felt permanent."],
  ["Sad", "Sometimes healing looks like pretending you are okay until you finally are."],
  ["Sad", "You left, but the empty spaces remembered you."],
  ["Sad", "I wish forgetting worked as easily as leaving."],
  ["Sad", "Some people become strangers while their memories stay familiar."],
  ["Sad", "I learned to hide heavy feelings behind ordinary conversations."],
  ["Sad", "The heart often understands the ending after the mind does."],
  ["Sad", "I do not hate you; I hate what we became."],
  ["Sad", "There are questions I stopped asking because I already know the answer."],
  ["Sad", "I still remember little things you probably forgot."],
  ["Sad", "Some wounds are invisible because they live in memories."],
  ["Sad", "I miss the version of us that never got a proper goodbye."],
  ["Sad", "It hurts when someone becomes a memory before you are ready."],
  ["Sad", "I have accepted the ending, but I still miss the beginning."],
  ["Sad", "Sometimes silence is just sadness without a place to go."],
  ["Sad", "I wish I could revisit the days before everything felt complicated."],
  ["Sad", "The loneliest feeling is missing someone who has moved on."],
  ["Sad", "I stopped waiting, but a small part of me still remembers."],
  ["Sad", "Some memories feel beautiful until they suddenly hurt."],
  ["Sad", "I learned that closure does not always arrive with an explanation."],
  ["Sad", "I can forgive you and still remember what it cost me."],
  ["Sad", "There are nights when being strong feels exhausting."],
  ["Sad", "I miss the conversations we never got to finish."],
  ["Sad", "Some endings leave questions instead of answers."],
  ["Sad", "I wish I could tell my past self what I know now."],
  ["Sad", "You can move forward and still carry a little sadness."],
  ["Sad", "I am healing from things I never found the courage to name."],
  ["Sad", "Sometimes the hardest goodbye is the one nobody says."],
  ["Sad", "I stopped checking for messages, but I still notice the silence."],
  ["Sad", "Some people leave footprints that time does not easily erase."],
  ["Sad", "I wish memories came with an off switch."],
  ["Sad", "I learned to cry quietly because not every pain needs an audience."],
  ["Sad", "The saddest memories are often the happiest ones we can no longer repeat."],
  ["Sad", "I still wonder if you ever think about the things we lost."],
  ["Sad", "Some days I miss you; other days I miss who I was with you."],
  ["Sad", "I am tired of pretending certain things never mattered."],
  ["Sad", "There are feelings I buried because carrying them became too heavy."],
  ["Sad", "Sometimes the heart wants an answer the past cannot give."],
  ["Sad", "I thought time would erase everything, but it only taught me to carry it."],
  ["Sad", "I do not want you back; I just want the memories to hurt less."],
  ["Sad", "Some people leave quietly and change your life loudly."],
  ["Sad", "I learned how to keep going with an unfinished story."],
  ["Sad", "The hardest thing was accepting that love could not fix everything."],
  ["Sad", "I miss being understood without having to explain myself."],
  ["Sad", "Some memories return when the world becomes quiet."],
  ["Sad", "I still remember how safe everything once felt."],
  ["Sad", "There is a special kind of sadness in becoming strangers."],
  ["Sad", "I wish we had known which moments were our last."],
  ["Sad", "Sometimes the heart grieves people who are still alive but no longer yours."],
  ["Sad", "I am okay, just not the same kind of okay as before."],
  ["Sad", "The silence after losing someone can feel louder than an argument."],
  ["Sad", "I stopped expecting apologies because healing had to begin without them."],
  ["Sad", "Some pain fades slowly because it meant something deeply."],
  ["Sad", "I miss the person I thought you would always be."],
  ["Sad", "I learned that letting go can hurt even when it is necessary."],
  ["Sad", "There are memories I keep because forgetting would feel like losing twice."],
  ["Sad", "Sometimes you can be surrounded by people and still feel alone."],
  ["Sad", "I wish I could tell you how different everything feels now."],
  ["Sad", "Some nights, the past feels closer than the present."],
  ["Sad", "I stopped blaming myself for an ending I could not control."],
  ["Sad", "It is strange how someone can be gone and still appear everywhere."],
  ["Sad", "I miss the comfort, not the confusion."],
  ["Sad", "Some wounds heal quietly while the world thinks you moved on overnight."],
  ["Sad", "I have made peace with the silence, even if I never wanted it."],
  ["Sad", "The hardest lesson was learning that not everyone stays."],
  ["Sad", "I remember enough to know why I had to leave."],
  ["Sad", "Sometimes you mourn a future that never happened."],
  ["Sad", "I wish the good memories did not come with such heavy feelings."],
  ["Sad", "I learned to let tears exist without calling them weakness."],
  ["Sad", "There are days when the smallest reminder changes my whole mood."],
  ["Sad", "I am slowly becoming someone who can remember without breaking."],
  ["Sad", "Some people are lessons that take years to understand."],
  ["Sad", "I no longer chase what chose to leave me behind."],
  ["Sad", "The heart can miss someone the mind knows it should release."],
  ["Sad", "I stopped asking why and started asking what I learned."],
  ["Sad", "There is courage in admitting that something still hurts."],
  ["Sad", "I do not regret loving; I regret forgetting myself while doing it."],
  ["Sad", "Some endings are painful because they were once beautiful."],
  ["Sad", "I am learning that missing someone does not mean going back."],
  ["Sad", "One day these memories will feel lighter than they do today."],
  ["Sad", "I carry the lesson, not the bitterness."],
  ["Sad", "I survived the days I thought would break me."],
  ["Sad", "Maybe healing is simply remembering without wanting to return."],
  ["Sad", "I am learning to carry the memory without carrying the pain."],
  ["Sad", "Sometimes healing begins when you stop pretending it never hurt."],
  ["Sad", "I wish some memories came with softer endings."],
  ["Sad", "There are days when I am fine until one song changes everything."],
  ["Sad", "I learned that missing someone and needing them are not the same thing."],
  ["Sad", "Some feelings stay quiet because words would make them heavier."],
  ["Sad", "I am slowly making peace with a story I never wanted to end."],
  ["Motivation", "Keep going; your story is not finished yet."],
  ["Motivation", "Small steps still count when they move you forward."],
  ["Motivation", "Believe in yourself before waiting for anyone else to do it."],
  ["Motivation", "A difficult season does not mean a failed life."],
  ["Motivation", "Every struggle is teaching you something strength cannot learn easily."],
  ["Motivation", "You are allowed to start small and dream big."],
  ["Motivation", "Progress matters even when nobody notices it."],
  ["Motivation", "Your future deserves more effort than your excuses."],
  ["Motivation", "Do not quit during the chapter that is building you."],
  ["Motivation", "Some doors open only after you keep knocking."],
  ["Motivation", "Discipline carries you when motivation disappears."],
  ["Motivation", "The person you want to become is built by today's choices."],
  ["Motivation", "One bad day cannot cancel years of effort."],
  ["Motivation", "Your pace can be slow without being wrong."],
  ["Motivation", "Keep showing up for the life you say you want."],
  ["Motivation", "Failure is information, not an identity."],
  ["Motivation", "You do not need a perfect beginning to create a great ending."],
  ["Motivation", "Your comfort zone cannot introduce you to your full potential."],
  ["Motivation", "Hard days are not proof that you should stop."],
  ["Motivation", "Let your actions become louder than your doubts."],
  ["Motivation", "The dream is still possible, even if the route changed."],
  ["Motivation", "You have survived every difficult day that came before this one."],
  ["Motivation", "Consistency can turn ordinary effort into extraordinary results."],
  ["Motivation", "Start before you feel completely ready."],
  ["Motivation", "Your next breakthrough may be hiding behind one more attempt."],
  ["Motivation", "Do not compare your first step with someone else's tenth year."],
  ["Motivation", "Patience is part of the work, not a delay to it."],
  ["Motivation", "Keep learning until the things that scare you become familiar."],
  ["Motivation", "Your future self is counting on the choices you make today."],
  ["Motivation", "A setback can redirect you without defeating you."],
  ["Motivation", "The road gets easier when you stop arguing with the process."],
  ["Motivation", "You can rebuild from almost anything."],
  ["Motivation", "Your effort matters even when the result arrives late."],
  ["Motivation", "Do not let temporary discomfort decide your permanent future."],
  ["Motivation", "Courage is simply moving while fear is still present."],
  ["Motivation", "Every morning gives you another chance to improve."],
  ["Motivation", "Make progress your habit, not your occasional mood."],
  ["Motivation", "Your goals need action more than they need announcements."],
  ["Motivation", "Keep working when nobody is clapping."],
  ["Motivation", "One focused year can change more than you imagine."],
  ["Motivation", "The hardest part is often beginning again."],
  ["Motivation", "You are capable of learning what you do not know yet."],
  ["Motivation", "Do not confuse slow growth with no growth."],
  ["Motivation", "Your dream deserves a version of you who refuses to quit."],
  ["Motivation", "Work on yourself until your confidence has evidence behind it."],
  ["Motivation", "A quiet effort can create a loud future."],
  ["Motivation", "Do not wait for motivation to rescue your discipline."],
  ["Motivation", "You can be tired and still take one more step."],
  ["Motivation", "Every mistake can become useful if you learn from it."],
  ["Motivation", "Your circumstances can change when your habits change."],
  ["Motivation", "Keep your vision bigger than today's frustration."],
  ["Motivation", "Success often starts with doing the boring things consistently."],
  ["Motivation", "You do not need everyone's belief to begin."],
  ["Motivation", "The person who keeps going eventually passes the person who keeps waiting."],
  ["Motivation", "Make today useful, even if it is not perfect."],
  ["Motivation", "Your potential grows whenever you challenge your limits."],
  ["Motivation", "Do not let yesterday decide what today can become."],
  ["Motivation", "A new result often requires an old comfort to be left behind."],
  ["Motivation", "You are closer to becoming stronger than you think."],
  ["Motivation", "Let discipline finish what motivation started."],
  ["Motivation", "Your story can change with one brave decision."],
  ["Motivation", "Keep planting even when the season looks empty."],
  ["Motivation", "The work you do privately can change your life publicly."],
  ["Motivation", "Your excuses cannot build the future you imagine."],
  ["Motivation", "Be patient with the version of you that is still learning."],
  ["Motivation", "Every attempt makes the next attempt smarter."],
  ["Motivation", "You can restart without erasing everything you have learned."],
  ["Motivation", "Your dream does not need permission from people who fear it."],
  ["Motivation", "Choose progress over perfection every single day."],
  ["Motivation", "The struggle will not last forever, but the strength can."],
  ["Motivation", "Keep moving even when the destination feels far away."],
  ["Motivation", "You are not behind; you are building at your own pace."],
  ["Motivation", "Do not stop because the first results are small."],
  ["Motivation", "Your habits are quietly writing your future."],
  ["Motivation", "Make your next decision better than your last one."],
  ["Motivation", "A strong life is built from ordinary disciplined days."],
  ["Motivation", "You do not need to see the whole staircase to take the next step."],
  ["Motivation", "The best time to improve is the day you stop making excuses."],
  ["Motivation", "Your future can be different because your choices can be different."],
  ["Motivation", "Let your setbacks teach you instead of defining you."],
  ["Motivation", "You have more room to grow than your current limits suggest."],
  ["Motivation", "Keep your promises to yourself."],
  ["Motivation", "The life you want will require effort from the version of you you are today."],
  ["Motivation", "Do not fear being a beginner."],
  ["Motivation", "Your consistency will eventually become your advantage."],
  ["Motivation", "Every difficult day you handle becomes proof of your strength."],
  ["Motivation", "Stay focused while the world is busy distracting you."],
  ["Motivation", "You can do hard things without having all the answers."],
  ["Motivation", "Make resilience part of your routine."],
  ["Motivation", "Your dream becomes real one repeated action at a time."],
  ["Motivation", "Do not wait for confidence; build it through action."],
  ["Motivation", "Keep going until your doubt has nothing left to say."],
  ["Motivation", "Your best chapter may still be unwritten."],
  ["Motivation", "One day you will be grateful you refused to stop."],
  ["Motivation", "Your effort may be invisible today, but it is not meaningless."],
  ["Motivation", "Keep choosing the next right step instead of fearing the whole journey."],
  ["Motivation", "You do not need a miracle when you are willing to keep working."],
  ["Motivation", "Let your patience be as strong as your ambition."],
  ["Motivation", "Your discipline can carry you farther than temporary inspiration."],
  ["Motivation", "The future changes when ordinary choices become intentional."],
  ["Life", "Life becomes richer when you notice the little things."],
  ["Life", "Not every chapter needs to make sense while you are living it."],
  ["Life", "There is no prize for rushing through your own life."],
  ["Life", "Sometimes losing something creates room for a better direction."],
  ["Life", "Peace is one of the quietest forms of success."],
  ["Life", "Life teaches lessons that no classroom can fully explain."],
  ["Life", "Ordinary moments often become precious after they are gone."],
  ["Life", "Growing up means learning what deserves your energy."],
  ["Life", "A different perspective can make the same life feel new."],
  ["Life", "Do not rush through moments you will someday miss."],
  ["Life", "Some people are chapters, not the entire story."],
  ["Life", "The best memories rarely arrive with a schedule."],
  ["Life", "Life feels lighter when gratitude becomes a daily habit."],
  ["Life", "You do not need everything figured out to move forward."],
  ["Life", "Some endings quietly make space for better beginnings."],
  ["Life", "Time reveals truths that conversations sometimes hide."],
  ["Life", "A peaceful life is not a boring life."],
  ["Life", "You can appreciate where you are while still wanting more."],
  ["Life", "The smallest joys are often the easiest to overlook."],
  ["Life", "Life changes when you stop measuring it against someone else's."],
  ["Life", "Not every delay is a denial; some are redirections."],
  ["Life", "Your current season is not your permanent address."],
  ["Life", "Sometimes the lesson is simply to let things be."],
  ["Life", "The people you love are part of what makes time meaningful."],
  ["Life", "Life is made of moments, not milestones alone."],
  ["Life", "You cannot control every event, but you can choose your response."],
  ["Life", "Some roads only make sense after you have walked them."],
  ["Life", "Happiness often hides inside ordinary routines."],
  ["Life", "There are seasons for building and seasons for resting."],
  ["Life", "Do not postpone living until everything feels perfect."],
  ["Life", "Time is precious because it never repeats itself."],
  ["Life", "Some goodbyes protect the life you are becoming."],
  ["Life", "A slow season can still be a meaningful season."],
  ["Life", "Life becomes calmer when expectations become realistic."],
  ["Life", "You are allowed to change the plans you once made."],
  ["Life", "Some people enter your life to teach, not to stay."],
  ["Life", "The present deserves attention because it will soon become memory."],
  ["Life", "Life is not a straight line; it is a collection of turns."],
  ["Life", "Sometimes getting lost helps you discover what matters."],
  ["Life", "The older you become, the more valuable peace feels."],
  ["Life", "A simple day can hold a beautiful memory."],
  ["Life", "Do not overlook the people who make normal days easier."],
  ["Life", "Life does not promise certainty, and that is part of its beauty."],
  ["Life", "You can begin again without calling the past a failure."],
  ["Life", "Every season has something to teach you."],
  ["Life", "Some things take longer because they are shaping you too."],
  ["Life", "The best parts of life cannot always be measured."],
  ["Life", "You do not need a perfect life to have meaningful days."],
  ["Life", "Let yourself enjoy the moment you are currently in."],
  ["Life", "Life becomes beautiful when comparison becomes gratitude."],
  ["Life", "Some memories are worth more than expensive things."],
  ["Life", "You can outgrow a place without hating what it once gave you."],
  ["Life", "The right pace is the one that lets you actually live."],
  ["Life", "Sometimes peace means accepting what you cannot change."],
  ["Life", "Your life deserves more attention than other people's timelines."],
  ["Life", "A difficult chapter does not ruin the whole book."],
  ["Life", "The people who stay during ordinary days are often the most valuable."],
  ["Life", "Life has a way of teaching patience through waiting."],
  ["Life", "Some answers arrive only after you stop forcing them."],
  ["Life", "The best moments are often too simple to plan."],
  ["Life", "You are allowed to enjoy life before everything is solved."],
  ["Life", "Change can be uncomfortable and still be necessary."],
  ["Life", "A meaningful life is built from small choices repeated over time."],
  ["Life", "Do not let temporary problems steal permanent moments."],
  ["Life", "There is beauty in becoming someone you did not expect to be."],
  ["Life", "Life feels different when you stop trying to control every outcome."],
  ["Life", "Sometimes walking away is how you protect your future."],
  ["Life", "The present is the only part of life you can actually hold."],
  ["Life", "Every person you meet leaves something behind: a memory or a lesson."],
  ["Life", "Some days are for achieving; others are for simply breathing."],
  ["Life", "Your story does not need to look like anyone else's."],
  ["Life", "A quiet life can still be a deeply successful one."],
  ["Life", "Do not forget to live while you are busy building."],
  ["Life", "Life gives meaning to the moments we choose to notice."],
  ["Life", "Some losses teach you what you were taking for granted."],
  ["Life", "You can miss the past without wanting to return to it."],
  ["Life", "The future is uncertain, but today is real."],
  ["Life", "Life gets lighter when you stop carrying what was never yours."],
  ["Life", "There is wisdom in knowing when enough is enough."],
  ["Life", "The people around you can change the way ordinary days feel."],
  ["Life", "A grateful heart notices what a restless mind overlooks."],
  ["Life", "Sometimes the best plan is to be present."],
  ["Life", "Your life is happening now, not someday."],
  ["Life", "Some seasons are quiet because growth is happening underneath."],
  ["Life", "You do not have to understand the whole journey to appreciate the view."],
  ["Life", "Life rewards patience in ways we often notice too late."],
  ["Life", "A meaningful life is not necessarily a loud one."],
  ["Life", "The older memories become, the more valuable the details feel."],
  ["Life", "Do not wait for a special day to appreciate an ordinary one."],
  ["Life", "Some chapters end because they have taught everything they came to teach."],
  ["Life", "Life becomes more peaceful when you stop forcing people to stay."],
  ["Life", "Every sunrise is a small reminder that beginnings are possible."],
  ["Life", "Your life can change without warning, so love the people you have today."],
  ["Life", "There is still beauty ahead that you have not met yet."],
  ["Life", "Make room for joy, even while you are figuring things out."],
  ["Life", "One day, today's ordinary moments may become your favorite memories."],
  ["Life", "Some of the best parts of life arrive without an announcement."],
  ["Life", "A good life is often quieter than the life people show online."],
  ["Life", "You can be grateful for yesterday and still be excited about tomorrow."],
  ["Life", "Sometimes the most important journey is the one back to yourself."],
  ["Self Love", "I am learning to love myself without needing a reason."],
  ["Self Love", "I deserve the same kindness I keep giving to everyone else."],
  ["Self Love", "Choosing myself is not selfish when I have spent years forgetting myself."],
  ["Self Love", "My worth does not rise or fall with someone's opinion."],
  ["Self Love", "I am enough, even on days when I feel unfinished."],
  ["Self Love", "I am becoming a safe place for my own heart."],
  ["Self Love", "I will not abandon myself just to keep someone close."],
  ["Self Love", "My peace deserves protection."],
  ["Self Love", "I am proud of how far I have come, even if I still have miles to go."],
  ["Self Love", "I can choose myself without feeling guilty about it."],
  ["Self Love", "I deserve patience from the person I spend every day with: me."],
  ["Self Love", "My mistakes are part of my story, not the measure of my worth."],
  ["Self Love", "I am allowed to grow beyond the person I used to be."],
  ["Self Love", "I do not need applause to recognize my own progress."],
  ["Self Love", "My flaws do not cancel the good inside me."],
  ["Self Love", "I am allowed to rest without earning it first."],
  ["Self Love", "I can love who I am while still working on who I want to become."],
  ["Self Love", "My boundaries are one of the ways I care for myself."],
  ["Self Love", "I do not need to shrink so other people can feel comfortable."],
  ["Self Love", "I am learning to enjoy my own company."],
  ["Self Love", "My past deserves compassion, not endless punishment."],
  ["Self Love", "I deserve relationships that feel safe, honest, and mutual."],
  ["Self Love", "I am more than the mistakes I made while learning."],
  ["Self Love", "I can say no without explaining my entire heart."],
  ["Self Love", "My happiness matters even when nobody else notices it."],
  ["Self Love", "I am becoming someone I can trust."],
  ["Self Love", "I no longer measure my worth by how useful I am to others."],
  ["Self Love", "I deserve the life I am patiently building."],
  ["Self Love", "I can forgive myself for not knowing then what I know now."],
  ["Self Love", "My healing does not need a deadline."],
  ["Self Love", "I am allowed to protect my energy."],
  ["Self Love", "I do not need to be perfect to be lovable."],
  ["Self Love", "I can leave what hurts me without hating myself for staying before."],
  ["Self Love", "My value remains even when someone chooses not to see it."],
  ["Self Love", "I am learning to speak to myself with the same softness I offer others."],
  ["Self Love", "I deserve peaceful mornings and quiet nights."],
  ["Self Love", "I do not need everyone to understand my choices."],
  ["Self Love", "I am allowed to outgrow old versions of myself."],
  ["Self Love", "My self-respect is more important than being universally liked."],
  ["Self Love", "I can be a work in progress and still be worthy today."],
  ["Self Love", "I am learning to celebrate small victories."],
  ["Self Love", "I trust myself a little more every time I keep a promise to myself."],
  ["Self Love", "I do not have to earn rest by breaking myself first."],
  ["Self Love", "My heart deserves gentleness after everything it has carried."],
  ["Self Love", "I am not behind; I am becoming."],
  ["Self Love", "I can start over without calling myself a failure."],
  ["Self Love", "My happiness is not something I have to apologize for."],
  ["Self Love", "I am worthy on my productive days and my quiet days."],
  ["Self Love", "I do not need someone else to complete the parts of me I am learning to love."],
  ["Self Love", "I am allowed to choose peace over people-pleasing."],
  ["Self Love", "My voice deserves to be heard, including by me."],
  ["Self Love", "I can be strong without becoming hard."],
  ["Self Love", "I deserve to feel at home in my own skin."],
  ["Self Love", "I am learning that solitude can be peaceful, not lonely."],
  ["Self Love", "My journey deserves respect even when it looks different from others."],
  ["Self Love", "I am not responsible for carrying everyone's emotions."],
  ["Self Love", "I choose authenticity over approval."],
  ["Self Love", "I deserve honesty from others and kindness from myself."],
  ["Self Love", "I am proud of every version of me that kept going."],
  ["Self Love", "I can release what no longer fits without questioning my worth."],
  ["Self Love", "My boundaries are not walls; they are doors with conditions."],
  ["Self Love", "I do not need to prove that I deserve love."],
  ["Self Love", "I am allowed to take up space in my own life."],
  ["Self Love", "My peace is not a luxury; it is a necessity."],
  ["Self Love", "I am learning to trust my instincts again."],
  ["Self Love", "I deserve to be celebrated by myself too."],
  ["Self Love", "I do not need to compare my chapter with anyone else's."],
  ["Self Love", "I can be gentle with myself while still holding myself accountable."],
  ["Self Love", "My identity is bigger than anyone's rejection."],
  ["Self Love", "I choose growth because I believe I am worth the effort."],
  ["Self Love", "I am allowed to change my mind when something no longer feels right."],
  ["Self Love", "I deserve friendships that do not require me to perform."],
  ["Self Love", "I am learning to stop chasing acceptance."],
  ["Self Love", "My heart does not need to apologize for needing care."],
  ["Self Love", "I can love myself without waiting to become perfect."],
  ["Self Love", "I deserve a life that does not constantly drain me."],
  ["Self Love", "I am becoming the person I once needed."],
  ["Self Love", "I will not use someone else's standards to measure my soul."],
  ["Self Love", "My progress counts even when it is invisible to others."],
  ["Self Love", "I am allowed to celebrate myself without feeling arrogant."],
  ["Self Love", "I can protect my peace without closing my heart."],
  ["Self Love", "I deserve a future that feels like mine."],
  ["Self Love", "I am learning that saying no can be an act of love toward myself."],
  ["Self Love", "My worth is not negotiable."],
  ["Self Love", "I can forgive myself and still choose better next time."],
  ["Self Love", "I deserve to feel proud when I look at the person I am becoming."],
  ["Self Love", "I am not my worst day."],
  ["Self Love", "I am not too much for the right people."],
  ["Self Love", "I am allowed to leave spaces where I constantly have to prove my value."],
  ["Self Love", "My happiness begins with how I treat myself when nobody is watching."],
  ["Self Love", "I deserve the same grace I give to people I love."],
  ["Self Love", "I am learning to stop abandoning my needs for someone else's comfort."],
  ["Self Love", "I can be independent without pretending I never need support."],
  ["Self Love", "I choose myself because I finally understand my own value."],
  ["Self Love", "I am worthy before I achieve anything."],
  ["Self Love", "I am allowed to heal at my own pace."],
  ["Self Love", "The relationship with myself deserves daily attention."],
  ["Self Love", "I will keep choosing the version of me that feels honest and free."],
  ["Self Love", "I deserve to speak to myself without cruelty."],
  ["Self Love", "My needs are allowed to matter in my own story."],
  ["Success", "Success begins when excuses stop making decisions for you."],
  ["Success", "Work quietly until your results have their own voice."],
  ["Success", "A dream becomes useful when you give it a plan."],
  ["Success", "Consistency can take you places motivation cannot."],
  ["Success", "The hardest work is often the work nobody sees."],
  ["Success", "Your effort today can become your freedom tomorrow."],
  ["Success", "Build yourself into the person who can handle the success you want."],
  ["Success", "Small progress becomes powerful when it never stops."],
  ["Success", "Discipline turns intentions into evidence."],
  ["Success", "A successful life is built on ordinary days done well."],
  ["Success", "Keep showing up, especially when the excitement fades."],
  ["Success", "Your habits are voting for the future you will eventually live."],
  ["Success", "Do not wait for the perfect opportunity; prepare for it."],
  ["Success", "Success is rarely sudden; it is usually accumulated."],
  ["Success", "Your first goal should be becoming better at what you do."],
  ["Success", "One focused year can change the direction of a life."],
  ["Success", "Do not confuse movement with meaningful progress."],
  ["Success", "The work you avoid may be the skill you most need."],
  ["Success", "Your future deserves today's uncomfortable decisions."],
  ["Success", "A setback can become useful if you refuse to waste the lesson."],
  ["Success", "Success requires patience because foundations take time."],
  ["Success", "Build skills that make opportunities easier to recognize."],
  ["Success", "You do not need to be the fastest; you need to remain consistent."],
  ["Success", "The people who win long-term learn to love the process."],
  ["Success", "Your competition is yesterday's version of you."],
  ["Success", "Do the small things well enough and they become big things."],
  ["Success", "A strong career is built long before the title arrives."],
  ["Success", "Your results eventually reveal your routines."],
  ["Success", "Do not chase applause; chase mastery."],
  ["Success", "The best investment is becoming harder to replace."],
  ["Success", "Success grows where discipline is stronger than mood."],
  ["Success", "Your goals need calendars, not just wishes."],
  ["Success", "Keep learning after the first success; that is how you keep it."],
  ["Success", "The road gets clearer when you take the next step."],
  ["Success", "You can change your future by changing what you repeat."],
  ["Success", "Hard work without direction is noise; work with purpose."],
  ["Success", "Make your standards higher than your excuses."],
  ["Success", "Your next level will require habits your current level does not."],
  ["Success", "Do not stop because the first result is small."],
  ["Success", "Every expert has a history of being a beginner."],
  ["Success", "Success often looks boring before it looks impressive."],
  ["Success", "Focus is a competitive advantage in a distracted world."],
  ["Success", "The work you do when nobody cares is what prepares you for when they do."],
  ["Success", "Your dream deserves more than occasional effort."],
  ["Success", "Do not let temporary comfort become a permanent ceiling."],
  ["Success", "A clear goal makes difficult days easier to navigate."],
  ["Success", "Keep improving the skill that creates your value."],
  ["Success", "Your future is being built by what you repeat today."],
  ["Success", "Success is often a collection of small promises kept."],
  ["Success", "Learn to enjoy progress before you reach the finish line."],
  ["Success", "Do not measure your journey only by visible results."],
  ["Success", "Patience protects good work from being abandoned too early."],
  ["Success", "The strongest businesses, careers, and lives are built on consistency."],
  ["Success", "Your opportunity may arrive after the moment you wanted to quit."],
  ["Success", "Preparation makes luck more useful."],
  ["Success", "Do not wait for confidence; let action create it."],
  ["Success", "A disciplined hour today can save months tomorrow."],
  ["Success", "Your potential means little until you put it into practice."],
  ["Success", "Keep your standards when nobody is watching."],
  ["Success", "Success is easier to sustain when it is built on character."],
  ["Success", "Make decisions your future self will respect."],
  ["Success", "Do not compare your beginning with someone else's established life."],
  ["Success", "Your pace matters less than your direction."],
  ["Success", "A difficult goal becomes manageable when broken into daily actions."],
  ["Success", "Work until your skills can speak for you."],
  ["Success", "Do not fear starting small; fear staying stuck."],
  ["Success", "Your habits can change your income, your confidence, and your options."],
  ["Success", "Success is not just reaching the goal; it is becoming capable along the way."],
  ["Success", "Build something that keeps working after motivation disappears."],
  ["Success", "The strongest advantage is the ability to keep learning."],
  ["Success", "Your next breakthrough may require one more uncomfortable attempt."],
  ["Success", "Do not let one failure become a permanent conclusion."],
  ["Success", "The future rewards people who prepare before they are noticed."],
  ["Success", "Stay focused while others are distracted by shortcuts."],
  ["Success", "Your work compounds when you keep improving it."],
  ["Success", "A slow climb is still a climb."],
  ["Success", "Do not sacrifice your long-term future for short-term comfort."],
  ["Success", "Your reputation is built through repeated actions, not one big moment."],
  ["Success", "The best time to become serious about your goals is before regret arrives."],
  ["Success", "Success asks for consistency long after excitement has left."],
  ["Success", "Create systems that make progress easier to repeat."],
  ["Success", "You cannot control every result, but you can control the quality of your effort."],
  ["Success", "Keep your vision clear when the path becomes messy."],
  ["Success", "A strong foundation makes future growth less fragile."],
  ["Success", "Do not spend more time announcing goals than working on them."],
  ["Success", "Your best opportunity may be the skill you have not mastered yet."],
  ["Success", "Every difficult project teaches you something valuable."],
  ["Success", "Success becomes sustainable when discipline becomes normal."],
  ["Success", "Keep going until the work you once feared becomes routine."],
  ["Success", "The goal is not to look successful; it is to become capable."],
  ["Success", "Your future can be built one focused decision at a time."],
  ["Success", "Do not underestimate the power of showing up every day."],
  ["Success", "The gap between wishing and achieving is filled with action."],
  ["Success", "Build quietly, learn constantly, and improve deliberately."],
  ["Success", "One day, the sacrifices behind your success will explain the result."],
  ["Success", "Make your work so useful that opportunities begin looking for you."],
  ["Success", "Long-term success is often built by people who can stay patient when nobody is impressed."],
  ["Success", "Your discipline becomes an asset when your circumstances change."],
  ["Success", "The best results come from work that survives your changing moods."],
  ["Success", "Keep building the skill that your future opportunities will require."],
];


const categories = [
  ["✦","All","All"],["⚡","Attitude","Attitude"],["♡","Love","Love"],["☾","Sad","Sad"],
  ["↗","Motivation","Motivation"],["♢","Life","Life"],["✿","Self Love","Self Love"],["◆","Success","Success"]
];

const categoryGrid=document.getElementById("categoryGrid");
const filters=document.getElementById("filters");
const grid=document.getElementById("quoteGrid");
const isCategoryPage=document.body.classList.contains("category-page");

const categoryMeta={
  "Attitude":{icon:"⚡",title:"Attitude Captions",desc:"Bold, confident captions for your strongest moments.",accent:"⚡"},
  "Love":{icon:"♡",title:"Love Captions",desc:"Romantic, heartfelt words for the people and moments you love.",accent:"♡"},
  "Sad":{icon:"☾",title:"Sad Captions",desc:"Quiet words for heartbreak, loneliness and difficult days.",accent:"☾"},
  "Motivation":{icon:"↗",title:"Motivational Captions",desc:"Focused words to keep you moving, growing and winning.",accent:"↗"},
  "Life":{icon:"♢",title:"Life Captions",desc:"Thoughtful captions about life, lessons, change and growth.",accent:"♢"},
  "Self Love":{icon:"✿",title:"Self Love Captions",desc:"Words about confidence, boundaries, healing and becoming yourself.",accent:"✿"},
  "Success":{icon:"◆",title:"Success Captions",desc:"Ambitious captions for goals, discipline, progress and achievement.",accent:"◆"}
};

function goCategory(key){
  if(key==="All"){ window.location.href="index.html#quotes"; return; }
  window.location.href=`category.html?category=${encodeURIComponent(key)}`;
}

if(!isCategoryPage){
  categories.forEach(([icon,name,key],i)=>{
    const el=document.createElement("button");
    el.className="cat"+(i===0?" active":"");
    el.innerHTML=`<div class="cat-icon">${icon}</div><span>${name}</span>`;
    el.onclick=()=>goCategory(key);
    categoryGrid?.appendChild(el);
  });
  categories.forEach(([_,name,key],i)=>{
    const el=document.createElement("button");
    el.className="filter"+(i===0?" active":"");
    el.textContent=name;
    el.onclick=()=>goCategory(key);
    filters?.appendChild(el);
  });
}

function smartOrder(list){
  const arr=[...list];
  for(let i=arr.length-1;i>0;i--){
    const j=(i*37+17)%(i+1);
    [arr[i],arr[j]]=[arr[j],arr[i]];
  }
  const out=[];
  while(arr.length){
    let pick=0;
    if(out.length){
      const lastWords=new Set(out[out.length-1][1].toLowerCase().replace(/[^a-z0-9 ]/g,'').split(/\s+/).slice(0,5));
      let best=-1,bestScore=999;
      arr.forEach((q,i)=>{
        const words=q[1].toLowerCase().replace(/[^a-z0-9 ]/g,'').split(/\s+/).slice(0,5);
        const overlap=words.filter(w=>lastWords.has(w)).length;
        if(overlap<bestScore){bestScore=overlap;best=i;}
      });
      pick=best<0?0:best;
    }
    out.push(arr.splice(pick,1)[0]);
  }
  return out;
}

function makeQuoteCard(tag,text,index){
  const card=document.createElement("article");
  card.className="quote-card";
  card.innerHTML=`<span class="tag">${tag}</span><blockquote>“${text}”</blockquote>
    <div class="card-bottom"><span>Captionza · ${String(index).padStart(2,"0")}</span><button class="copy" aria-label="Copy caption">Copy</button></div>`;
  card.querySelector(".copy").onclick=()=>copy(text);
  return card;
}

function render(){
  if(!grid) return;
  grid.innerHTML="";
  const raw=current==="All"?quotes:quotes.filter(q=>q[0]===current);
  const list=smartOrder(raw);
  list.slice(0,visible).forEach(([tag,text],i)=>grid.appendChild(makeQuoteCard(tag,text,i+1)));
  const load=document.getElementById("loadMore");
  if(load) load.style.display=visible<list.length?"block":"none";
}

function copy(text){
  navigator.clipboard?.writeText(text);
  const t=document.getElementById("toast");
  if(t){t.textContent="Caption copied ✓";t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1600)}
}

function randomQuote(){
  const q=quotes[Math.floor(Math.random()*quotes.length)][1];
  const hero=document.getElementById("heroQuote");
  const featured=document.getElementById("featuredQuote");
  if(hero) hero.textContent=q;
  if(featured) featured.textContent=`“${q}”`;
}

if(!isCategoryPage){
  let current="All", visible=6;
  document.getElementById("copyFeatured")?.addEventListener("click",()=>copy(document.getElementById("featuredQuote").textContent.replace(/[“”]/g,"")));
  document.getElementById("randomHero")?.addEventListener("click",randomQuote);
  document.getElementById("randomCta")?.addEventListener("click",()=>{randomQuote();window.scrollTo({top:0,behavior:"smooth"})});
  document.getElementById("loadMore")?.addEventListener("click",()=>{visible+=6;render()});
  document.getElementById("themeBtn")?.addEventListener("click",()=>{
    document.body.classList.toggle("dark");
    document.getElementById("themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾";
  });
  render();
}else{
  const params=new URLSearchParams(location.search);
  const requested=params.get("category")||"";
  const meta=categoryMeta[requested];
  const safeCategory=meta?requested:"Attitude";
  const pageTitle=document.getElementById("categoryTitle");
  const pageDesc=document.getElementById("categoryDescription");
  const pageIcon=document.getElementById("categoryIcon");
  const count=document.getElementById("categoryCount");
  document.title=`${safeCategory} Captions — Captionza`;
  if(pageTitle) pageTitle.textContent=categoryMeta[safeCategory].title;
  if(pageDesc) pageDesc.textContent=categoryMeta[safeCategory].desc;
  if(pageIcon) pageIcon.textContent=categoryMeta[safeCategory].icon;
  const categoryQuotes=quotes.filter(q=>q[0]===safeCategory);
  if(count) count.textContent=`${categoryQuotes.length} captions`;
  var current=safeCategory;
  var visible=6;
  document.getElementById("loadMore")?.addEventListener("click",()=>{visible+=6;render()});
  render();
  document.querySelectorAll(".category-nav-link").forEach(link=>{
    link.addEventListener("click",e=>{
      const key=link.dataset.category;
      if(key) { e.preventDefault(); goCategory(key); }
    });
  });
}
